### ISSUE TITLE
Exposing Micronaut JSON Core

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-toml#65]
### Issue description

Should this module [expose Micronaut JSON Core](https://github.com/micronaut-projects/micronaut-toml/blob/master/toml/build.gradle#L7)? Or should that be `implementation` instead of `api`.

**Comment by sdelamo** [comment]
ping @yawkat @melix

**Comment by melix** [comment]
I don't have the expertise to say if it's intentional or not, but using `api` is currently correct, since JSON is exposed in public APIs: https://github.com/micronaut-projects/micronaut-toml/blob/master/toml/src/main/java/io/micronaut/toml/Parser.java#L60

**Comment by yawkat** [comment]
`Parser` is `@Internal` and only meant to be used within the module

**Comment by melix** [comment]
Then if no class from Micronaut JSON is exposed in the public API, then we can make it `implementation`.

**Comment by yawkat** [comment]
ok i will push the change.
